name: build new decK
on:
  workflow_dispatch:

jobs:

    deployment:
        name: "to the moon 🚀"
        strategy:
          matrix:
            os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Install go
            uses: actions/setup-go@v3
            with:
              go-version: 1.18

          - name: Go build
            run: |
              CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o deck
          
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: decK-${{ matrix.os }}
              path: deck
